--- Makefile	2011-08-31 22:10:32.000000000 -0700
+++ Makefile	2011-09-24 16:26:19.331108636 -0700
@@ -354,7 +355,15 @@
 		   -fno-strict-aliasing -fno-common \
 		   -Werror-implicit-function-declaration \
 		   -Wno-format-security \
-		   -fno-delete-null-pointer-checks
+		   -fno-delete-null-pointer-checks \
+		-mfloat-abi=softfp -funroll-loops \
+                -floop-interchange -floop-strip-mine -floop-block \
+                -fpredictive-commoning -ftree-vectorize \
+                -funswitch-loops -fgcse-after-reload -fipa-cp-clone \
+                -pipe \
+                -marm -march=armv7-a -mtune=cortex-a9 \
+                -mfpu=neon
+
 #change@wtl.kSingh - enabling FIPS mode - starts
 ifeq ($(USE_SEC_FIPS_MODE),true)
 KBUILD_CFLAGS += -DSEC_FIPS_ENABLED
